version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./hackaton_back
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build:
      context: ./hackaton_front
    ports:
      - "3000:3000"

volumes:
  pgdata:
